#pragma once

#include "traits.hpp"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <iomanip>

namespace zeroclaw::memory {

inline constexpr const char* SNAPSHOT_FILENAME = "MEMORY_SNAPSHOT.md";

inline constexpr const char* SNAPSHOT_HEADER = 
    "# 🧠 ZeroClaw Memory Snapshot\n\n"
    "> Auto-generated by ZeroClaw. Do not edit manually unless you know what you're doing.\n"
    "> This file is the \"soul\" of your agent — if `brain.db` is lost, start the agent\n"
    "> in this workspace and it will auto-hydrate from this file.\n\n";

inline std::filesystem::path snapshot_path(const std::filesystem::path& workspace_dir) {
    return workspace_dir / SNAPSHOT_FILENAME;
}

inline std::vector<std::pair<std::string, std::string>> parse_snapshot(const std::string& input) {
    std::vector<std::pair<std::string, std::string>> entries;
    std::optional<std::string> current_key;
    std::string current_content;
    
    std::istringstream stream(input);
    std::string line;
    
    while (std::getline(stream, line)) {
        size_t start = line.find_first_not_of(" \t\r\n");
        std::string trimmed = (start != std::string::npos) ? line.substr(start) : "";
        
        if (trimmed.rfind("### 🔑 `", 0) == 0 && trimmed.size() > 10 && trimmed.back() == '`') {
            if (current_key) {
                std::string content = current_content;
                size_t cs = content.find_first_not_of(" \t\r\n");
                size_t ce = content.find_last_not_of(" \t\r\n");
                if (cs != std::string::npos && ce != std::string::npos) {
                    content = content.substr(cs, ce - cs + 1);
                }
                if (!content.empty()) {
                    entries.emplace_back(*current_key, content);
                }
            }
            
            std::string key = trimmed.substr(8, trimmed.size() - 9);
            current_key = key;
            current_content.clear();
        } else if (current_key) {
            if (trimmed.rfind("*Created:", 0) == 0 || trimmed == "---") {
                continue;
            }
            if (!current_content.empty() || !trimmed.empty()) {
                if (!current_content.empty()) current_content += '\n';
                current_content += line;
            }
        }
    }
    
    if (current_key) {
        std::string content = current_content;
        size_t cs = content.find_first_not_of(" \t\r\n");
        size_t ce = content.find_last_not_of(" \t\r\n");
        if (cs != std::string::npos && ce != std::string::npos) {
            content = content.substr(cs, ce - cs + 1);
        }
        if (!content.empty()) {
            entries.emplace_back(*current_key, content);
        }
    }
    
    return entries;
}

inline bool should_hydrate(const std::filesystem::path& workspace_dir) {
    auto db_path = workspace_dir / "memory" / "brain.db";
    auto snapshot = snapshot_path(workspace_dir);
    
    bool db_missing_or_empty = true;
    if (std::filesystem::exists(db_path)) {
        auto size = std::filesystem::file_size(db_path);
        db_missing_or_empty = size < 4096;
    }
    
    return db_missing_or_empty && std::filesystem::exists(snapshot);
}

}
